
export const OPEN_CHANNEL = "OPEN_CHANNEL"

export const REQUEST_SUBSCRIPTIONS = "REQUEST_SUBSCRIPTIONS"
export const RECEIVE_SUBSCRIPTIONS = "RECEIVE_SUBSCRIPTIONS"
export const FAILED_FETCH_SUBSCRIPTIONS = "FAILED_FETCH_SUBSCRIPTIONS"
